### ISSUE TITLE
Add periodic dependency updater like Dependabot

### ISSUE THREAD

**Issue by nifadyev** [evrone/evrone-django-template#15]
Dependency updater will help to keep project dependencies up to date. Relevant dependencies reduce security issues, allow using the latest features, but may break compatibility. As a result, dependencies updater is helpful, but their changes should be validated and tested manually.

The first and obvious option is [Dependabot](https://github.com/dependabot). It is the default Github updater, and it is widely used in many projects. However, sometimes it lacks some useful features and may spam PRs if it is improperly configured (like any other updater). Also, only Github is supported, so migration to other hosting platform may be difficult

Another option is [Renovate](https://www.mend.io/renovate/). It supports many hosting platforms, its development is more active and PRs description contains more helpful information.

Compare [dependabot PR](https://github.com/fandsdev/django/pull/733) and [renovate PR](https://github.com/tough-dev-school/education-backend/pull/2387)

**Comment by soltanoff** [comment]
It would be nice to have the opportunity

**Comment by nifadyev** [comment]
@soltanoff , could you please have a look at #16 ?
