### ISSUE TITLE
Replace safety to alternative vulnerability scanner

### ISSUE THREAD

**Issue by nifadyev** [evrone/evrone-django-template#17]
Reasoning:

- Command `safety check` is [deprecated](https://github.com/pyupio/safety/blob/main/CHANGELOG.md#other). Alternative command `safety scan` requires authorization to Safety platform
- Supports only `python` while alternatives support many languages allowing to create config for most company projects
- `safety` does not officially support latest python versions [setup.cfg](https://github.com/pyupio/safety/blob/main/setup.cfg#L16-L30)
- Has heavy dependencies like `pydantic`, `Click`, `jinja2`, which are usually installed as production dependencies on python based projects
- Alternative scanners on [github](https://github.com/topics/vulnerability-scanners), [trivy](https://aquasecurity.github.io/trivy/v0.56/) - the most starred

**Comment by nifadyev** [comment]
Below is tool comparison with attached output (tested on [worklogs-toggl](https://github.com/evrone-erp/worklogs-toggl)):

- [safety](https://github.com/pyupio/safety/) - current option, command `safety check` with config `.safey-policy.yml` has been run.
- [trivy](https://aquasecurity.github.io/trivy) - command `docker run -v /var/run/docker.sock:/var/run/docker.sock -v .:/app aquasec/trivy:0.57.0 repo /app --db-repository public.shturval.tech/trivy-db`. Has issues with pulling `ghcr.io`, that is why alternative registry is necessary
- [dep-scan](https://github.com/owasp-dep-scan/dep-scan) - command `docker run --rm -v $PWD:/app ghcr.io/owasp-dep-scan/dep-scan --src /app --reports-dir /app/reports`. Most detailed and "deep" scan. Shows issues with both `python` dependencies` and `docker` images. Also scans dependencies of dependencies. Has [Github Action](https://github.com/AppThreat/dep-scan-action/blob/master/action.yml) with paywall, but this action could be easily copied and used free
- [pip-audit](https://github.com/pypa/pip-audit) - command `pip-audit`. Output mostly the same as for `safety`

`pre-commit` hook could be implemented similarly:

```yaml
- id: trivyconfig-docker
  name: trivyconfig-docker
  entry: aquasec/trivy:0.56.2 config --cache-dir /src/.pre-commit-trivy-cache --exit-code 1
  language: docker_image
  pass_filenames: false
```

I suggest use vulnerability checks only on `CI` and optionally `pre-commit` level. It is harmful to pollute local virtual environment and these checks should not be executed so often in comparison with linters, for example
[trivy.log](https://github.com/user-attachments/files/17656899/trivy.log)
[dep-scan.log](https://github.com/user-attachments/files/17656902/dep-scan.log)
[pip-audit.log](https://github.com/user-attachments/files/17656903/pip-audit.log)
[safety.log](https://github.com/user-attachments/files/17656907/safety.log)

**Comment by soltanoff** [comment]
@nifadyev, hi! 

Thank you for researching. As it seems to me we may choose [pip-audit](https://github.com/pypa/pip-audit) instead of [safety](https://github.com/pyupio/safety/) due to [safety](https://github.com/pyupio/safety/) has badly package dependency on it side that often breaks the main dependency of our projects.

**Comment by nifadyev** [comment]
Just found out another option - [grype](https://github.com/anchore/grype). It is used as [github action](https://github.com/anchore/scan-action) is most of our internal projects.
